services:
  next-service:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "80:3000"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - redis


  postgres:
    image: "postgres:17.4"
    ports: 
      -  "5435:5432" 
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/


  redis:
    image: "redis:8.0.0-alpine"
    ports:
      - "6380:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
